### PR TITLE
Removed EWS support, it's deprecated only in Exchange Online

### PR DESCRIPTION
**Pull request by Kimzi**
Removed everything EWS.

### CODE REVIEW

**Comment by tomaskovacik** [comment]
how about on-premise installations?

**Comment by Kimzi** [comment]
@tomaskovacik You are correct, Microsoft revealed they would change this even on on prem Exchange several years ago so I just figured they had but I cannot find anything about it now. Will close this again, sorry for not checking.

**Comment by tomaskovacik** [comment]
https://techcommunity.microsoft.com/t5/exchange-team-blog/upcoming-api-deprecations-in-exchange-web-services-for-exchange/bc-p/2902173/highlight/true#M31548

**Comment by Kimzi** [comment]
@tomaskovacik, That is not what I was referring to, though I cannot seem to find anything about it anymore. Still, I should have checked again beforehand.
I found this though, so it seems they are still working on something : https://techcommunity.microsoft.com/t5/exchange-team-blog/exchange-server-roadmap-update/ba-p/3421389

**Pull request closed without merging**
